---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - name: backend
      port: 9000
      nodePort: {{ .Values.deployments.backend.nodePort }}
  selector:
    app: backend


