---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 80
      nodePort: {{ .Values.deployments.frontend.nodePort }}
  selector:
    app: frontend
